### ISSUE TITLE
Feature: User can sign up / sign in / sign out

### ISSUE THREAD

**Issue by jadenbertino** [jadenbertino/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign up / sign in / sign out

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If user is signed out:
- all content will be locked
- sign in / sign up prompt

If user is signed in:
- all page content will be available
- select / create new user page will display "sign out" button

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] new firebase project
- [x] new firebase auth
- [x] import hooks from previous projects
  - [x] signin
  - [x] signout
  - [x] signup
  - [x] authcontext
  - [x] useauthcontext 
- [x] setup authcontext provider
- [x] don't display any content until auth check is complete
- [x] create signup page
  - [ ] html
  - [ ] css
  - [ ] track forms with state
  - [ ] submit executes useSignUp hook + redirects
- [x] create signin page
  - [ ] html
  - [ ] css
  - [ ] track forms with state
  - [ ] submit executes useSignIn hook + redirects
- [x] create home component
  - [ ]  if user is signed in -> display sign out btn, which when clicked executes useSignOut
  - [ ] if user is signed out -> display sign up & sign in btn, which each link to their respective pages
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
