### ISSUE TITLE
Feature: User can create new conversation or select an existing one

### ISSUE THREAD

**Issue by jadenbertino** [jadenbertino/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a new "person" that they will have a conversation with. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The home page will look like netflix.
User can choose an existing conversation or create a new one.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/87284530/231294375-04d99fdd-38e1-4fae-8d5c-8117f9b09c88.png)
![image](https://user-images.githubusercontent.com/87284530/231324652-b805939c-ce8b-4e41-8d0b-449841214c6f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Initialize firestore service + SDK
- [x] user signup => create document for user in /users/{userID}
- [x] Setup "new conversation" page
  - [x] html
  - [x] css
  - [x] store form with state
  - [x] new conversation => create document for that conversation in /users/{userID}/conversations/{conversationID}
- [x] Setup select conversation page
  - [x] html
  - [x] css
  - [x] click existing user => routes to /conversations/{id}
  - [x] click new user => routes to "new conversation" page detailed above
  - [x] setup max height + scroll
- [x] Store conversations within the user doc inside a COLLECTION rather than an array
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
