### ISSUE TITLE
Feature: User can view existing conversation history + add new content to it

### ISSUE THREAD

**Issue by jadenbertino** [jadenbertino/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view existing conversation history + add new content to it

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User navigates to /conversations/{conversationID}
Conversation history will display like iMessage
Buttons to add to 'sent' and 'received' messages

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
ignore the bottom right "create new message" component for now

![image](https://user-images.githubusercontent.com/87284530/231326105-49011d93-b631-4821-845b-bf5727078cd1.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] get conversation id from route
- [x] fetch conversation, store in state
- [x] Create navbar
  - [x] display conversation name
  - [x] display conversation profile photo
  - [x] home button to go to home route
- [x] Can view conversation history
  - [x] get conversation content from conversation state
  - [x] map through content
    - [x] SENT messages are align right, blue bg
    - [x] RECEIVED messages are align left, pink bg
  - [x] window is fixed but you can scroll through it's content 1
- [x] messages auto scroll to bottom if it overflows 
- [x] can add to conversation history
  - [x] add SENT message  = popup with textarea => submit uploads to conversation db with property "type: SENT"
  - [x] add RECEIVED message = popup with textarea => submit uploads to conversation db with property "type: RECEIVED"
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.

**Comment by jadenbertino** [comment]
- [ ] change firestore structure to /users/{userID}/conversations/{conversationID}.messages
