### ISSUE TITLE
Feature: User can generate new message via openAI integration

### ISSUE THREAD

**Issue by jadenbertino** [jadenbertino/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click "generate" button to generate a list of potential messages to send
User can also optionally provide additional prompts beforehand to fine-tune the message creation

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
This feature concerns the "Create New Message" section on the bottom right of the screenshot:

![image](https://user-images.githubusercontent.com/87284530/231328086-cee056e8-52c8-4ddc-9e19-e47e7f04d39c.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create form
  - [x] html 
  - [x] css
  - [x] state to track all form controls
  - [ ] fetch user document in db => prefill "global prompts" section
  - [ ] fetch conversation document in db => prefill "conversation prompts" section
- [x] Create prompt message as state
  - [x] get conversation history
  - [x] get all prompts
  - [x] create my own formatting / prompting that is used every time a user hits "generate"
  - [x] combine all of the above into one prompt, store as state
  - [x] prompt openAI api
  - [x] get response
  - [x] insert response into suggested messages
  - [x] bullet points should be one click copy buttons
- **Clean Up**
  - [x] condense modal state into one
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
