### ISSUE TITLE
Feature: User can edit & delete a PERSON they are having a conversation with

### ISSUE THREAD

**Issue by jadenbertino** [jadenbertino/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can edit & delete a PERSON they are having a conversation with

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/87284530/231329767-d3160f4c-51ee-4a7e-b603-76a4240787ac.png)
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [ ] duplicate "new conversation" component
- [ ] get conversation id from url params
- [ ] fetch conversation from db
- [ ] prefill name, & img url
- [ ] button interactions
  - [ ] save => updates conversation doc
  - [ ] cancel => return to conversation page using conversation id
  - [ ] delete => confirm modal
    - [ ] confirm delete => deletes doc
    - [ ] cancel => closes modal
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
