### ISSUE TITLE
Feature: User can edit, delete, and insert new messages into conversation history

### ISSUE THREAD

**Issue by jadenbertino** [jadenbertino/ajax-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can hover over message to display options to:

| Hover | Modal |
| --- | --- |
| Insert message above | write new content + save or cancel | 
| Insert message below | write new content + save or cancel |
| Edit content of the message | edit content + save or cancel | 
| Delete the message | Confirm or Cancel Delete | 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/87284530/231331337-cbbfebbe-cec2-4c44-a9db-116444fff045.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] all messages will have all 4 buttons, but are set to display none
  - [ ] when message is hovered, those buttons become visible
- [ ] insert above btn click => launches modal
  - [ ] textarea, linked to state
  - [ ] submit => adds message to db before the current message
  - [ ] cancel => closes the modal
- [ ] insert below btn click => launches modal
  - [ ] textarea, linked to state
  - [ ] submit => adds message to db before the current message
  - [ ] cancel => closes the modal
- [ ] delete btn click => modal
  - [ ] cancel => closes modal
  - [ ] confirm => deletes that message from conversation in db
- [ ] edit btn click => modal
  - [ ] textarea, linked to state
    - [ ] pre-populates with original message
  - [ ] cancel => closes modal
  - [ ] confirm => edits message in db
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
