### ISSUE TITLE
Feature: User can import message history via screenshot upload

### ISSUE THREAD

**Issue by jadenbertino** [jadenbertino/ajax-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can take a screenshot of the conversation and upload the screenshot to the app in order to quickly add to the conversation history

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Add "import from screenshot" button to conversation component, it will be a form file upload control. track with state.
- [ ] file validation to ensure it's a photo
- [ ] send photo to OCR api
- [ ] extract every message from photo
  - [ ] text is on left half = received
  - [ ] text is on right half = sent message
  - [ ] add each message to an array. each message will have a TYPE (sent / received) and a CONTENT property
- [ ] remove any messages in the screenshot that are already in the conversation history
- [ ] show user a preview of the new conversation history
- [ ] user can confirm or cancel the import
  - [ ] cancel => close modal
  - [ ] confirm => update conversation history in db
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
